[build]
builder = "NIXPACKS"

[deploy]
# Run your app with gunicorn, pointing to run:app
startCommand = "gunicorn run:app --bind 0.0.0.0:$PORT"

# Run migrations automatically after each deploy
[[deploy.hooks]]
command = "flask db upgrade"

# Cron job to handle expired subscriptions daily at midnight
[cron]
schedule = "0 0 * * *"
command = "flask subscriptions:downgrade"
