"""Implement one-time payment subscription system

Revision ID: 673c2d769591
Revises: fb7170deab93
Create Date: 2025-08-27 22:45:04.073747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673c2d769591'
down_revision = 'fb7170deab93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('paystack_plan_code')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('paystack_subscription_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_subscription_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_plan_code', sa.VARCHAR(length=100), nullable=False))

    op.drop_table('payment')
    # ### end Alembic commands ###
